gui:
  language: en
  timeFormat: 2006/01/02
  showRandomTip: false
  border: single
git:
  diffRenderers:
    - command: difft --color=always
      type: extDiff
  log:
    order: default
  branchLogCmd: git log --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  fetchAll: false
update:
  method: never
disableStartupPopups: true
