# Palette:
# - primary: blue-cyan (75)
# - secondary: blue-gray (67)

main_window_color = default

state_line_color = 67
state_flags_color = 75:b

empty_tag_color = 67

color1 = 75
color2 = 67

progressbar_color = 67:b
progressbar_elapsed_color = 75:b

alternative_ui_separator_color = 67:b

window_border_color = 67
active_window_border = 75

song_columns_list_format = (20)[75]{a} (6f)[67]{NE} (50)[white]{t|f:Title} (20)[67]{b} (7f)[67]{lr:Length}
song_list_format = {$(75)%a$(end) - }{%t}|{$(75)%f$(end)}$R{$(67)%l$(end)}
song_status_format = {{$(75)%a$(end){ $(67)"%b"$(end){ $(67)(%y)$(end)}} - }{%t}}|{$(75)%f$(end)}
song_library_format = {%n - }{%t}|{$(75)%f$(end)}

current_item_prefix = $(75)$r
current_item_suffix = $/r$(end)
current_item_inactive_column_prefix = $(67)$r
current_item_inactive_column_suffix = $/r$(end)
